-- MySQL Script generated by MySQL Workbench
-- 04/11/15 20:12:26
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema VeganHeaven
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema VeganHeaven
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `VeganHeaven` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `VeganHeaven` ;

-- -----------------------------------------------------
-- Table `VeganHeaven`.`Paniers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `VeganHeaven`.`Paniers` (
  `idPaniers` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`idPaniers`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `VeganHeaven`.`Members`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `VeganHeaven`.`Members` (
  `idMembers` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(50) NULL,
  `password` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `TelephoneFixe` INT(10) NULL,
  `TelephoneMobile` INT(10) NULL,
  `Adresse` VARCHAR(255) NULL,
  `administrateur` TINYINT(1) NULL,
  `Paniers_idPaniers` INT NOT NULL,
  PRIMARY KEY (`idMembers`),
  CONSTRAINT `fk_Members_Paniers1`
    FOREIGN KEY (`Paniers_idPaniers`)
    REFERENCES `VeganHeaven`.`Paniers` (`idPaniers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Members_Paniers1_idx` ON `VeganHeaven`.`Members` (`Paniers_idPaniers` ASC);


-- -----------------------------------------------------
-- Table `VeganHeaven`.`Annonces`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `VeganHeaven`.`Annonces` (
  `idAnnonces` INT NOT NULL AUTO_INCREMENT,
  `Members_idMembers` INT NOT NULL,
  `Produit` VARCHAR(45) NULL,
  `Prix` INT NOT NULL,
  `Date` DATE NULL,
  `Description` VARCHAR(255) NULL,
  `Url_Image` VARCHAR(255) NULL,
  PRIMARY KEY (`idAnnonces`),
  CONSTRAINT `fk_Annonces_Members`
    FOREIGN KEY (`Members_idMembers`)
    REFERENCES `VeganHeaven`.`Members` (`idMembers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Annonces_Members_idx` ON `VeganHeaven`.`Annonces` (`Members_idMembers` ASC);


-- -----------------------------------------------------
-- Table `VeganHeaven`.`Transactions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `VeganHeaven`.`Transactions` (
  `idTransactions` INT NOT NULL AUTO_INCREMENT,
  `Annonces_idAnnonces` INT NOT NULL,
  `AdresseEchange` VARCHAR(45) NULL,
  `Date` DATE NULL,
  `Effectuee` TINYINT(1) NULL,
  PRIMARY KEY (`idTransactions`),
  CONSTRAINT `fk_Transactions_Annonces1`
    FOREIGN KEY (`Annonces_idAnnonces`)
    REFERENCES `VeganHeaven`.`Annonces` (`idAnnonces`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Transactions_Annonces1_idx` ON `VeganHeaven`.`Transactions` (`Annonces_idAnnonces` ASC);


-- -----------------------------------------------------
-- Table `VeganHeaven`.`Categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `VeganHeaven`.`Categories` (
  `idCategories` INT NOT NULL AUTO_INCREMENT,
  `Ajout` VARCHAR(100) NULL,
  `Descripif` VARCHAR(255) NULL,
  PRIMARY KEY (`idCategories`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `VeganHeaven`.`Annonces_Categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `VeganHeaven`.`Annonces_Categories` (
  `Annonces_idAnnonces` INT NOT NULL,
  `Categories_idCategories` INT NOT NULL,
  PRIMARY KEY (`Annonces_idAnnonces`, `Categories_idCategories`),
  CONSTRAINT `fk_Annonces_has_Categories_Annonces1`
    FOREIGN KEY (`Annonces_idAnnonces`)
    REFERENCES `VeganHeaven`.`Annonces` (`idAnnonces`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Annonces_has_Categories_Categories1`
    FOREIGN KEY (`Categories_idCategories`)
    REFERENCES `VeganHeaven`.`Categories` (`idCategories`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Annonces_has_Categories_Categories1_idx` ON `VeganHeaven`.`Annonces_Categories` (`Categories_idCategories` ASC);

CREATE INDEX `fk_Annonces_has_Categories_Annonces1_idx` ON `VeganHeaven`.`Annonces_Categories` (`Annonces_idAnnonces` ASC);


-- -----------------------------------------------------
-- Table `VeganHeaven`.`Appreciations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `VeganHeaven`.`Appreciations` (
  `idAvis` INT NOT NULL AUTO_INCREMENT,
  `Date` DATE NULL,
  `Note` INT NULL,
  PRIMARY KEY (`idAvis`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `VeganHeaven`.`Members_has_Appreciations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `VeganHeaven`.`Members_has_Appreciations` (
  `Members_idMembers` INT NOT NULL,
  `Appreciations_idAvis` INT NOT NULL,
  PRIMARY KEY (`Members_idMembers`, `Appreciations_idAvis`),
  CONSTRAINT `fk_Members_has_Appreciations_Members1`
    FOREIGN KEY (`Members_idMembers`)
    REFERENCES `VeganHeaven`.`Members` (`idMembers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Members_has_Appreciations_Appreciations1`
    FOREIGN KEY (`Appreciations_idAvis`)
    REFERENCES `VeganHeaven`.`Appreciations` (`idAvis`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Members_has_Appreciations_Appreciations1_idx` ON `VeganHeaven`.`Members_has_Appreciations` (`Appreciations_idAvis` ASC);

CREATE INDEX `fk_Members_has_Appreciations_Members1_idx` ON `VeganHeaven`.`Members_has_Appreciations` (`Members_idMembers` ASC);


-- -----------------------------------------------------
-- Table `VeganHeaven`.`Post_Forum`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `VeganHeaven`.`Post_Forum` (
  `idPost_Forum` INT NOT NULL AUTO_INCREMENT,
  `Members_idMembers` INT NOT NULL,
  `Date` DATE NULL,
  PRIMARY KEY (`idPost_Forum`),
  CONSTRAINT `fk_Post_Forum_Members1`
    FOREIGN KEY (`Members_idMembers`)
    REFERENCES `VeganHeaven`.`Members` (`idMembers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Post_Forum_Members1_idx` ON `VeganHeaven`.`Post_Forum` (`Members_idMembers` ASC);


-- -----------------------------------------------------
-- Table `VeganHeaven`.`Topic`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `VeganHeaven`.`Topic` (
  `idTopic` INT NOT NULL AUTO_INCREMENT,
  `Votes` INT NULL,
  `Vues` INT NULL,
  `Tags` VARCHAR(45) NULL,
  PRIMARY KEY (`idTopic`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `VeganHeaven`.`Post_Forum_Topic`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `VeganHeaven`.`Post_Forum_Topic` (
  `Post_Forum_idPost_Forum` INT NOT NULL,
  `Topic_idTopic` INT NOT NULL,
  PRIMARY KEY (`Post_Forum_idPost_Forum`, `Topic_idTopic`),
  CONSTRAINT `fk_Post_Forum_has_Topic_Post_Forum1`
    FOREIGN KEY (`Post_Forum_idPost_Forum`)
    REFERENCES `VeganHeaven`.`Post_Forum` (`idPost_Forum`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Post_Forum_has_Topic_Topic1`
    FOREIGN KEY (`Topic_idTopic`)
    REFERENCES `VeganHeaven`.`Topic` (`idTopic`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Post_Forum_has_Topic_Topic1_idx` ON `VeganHeaven`.`Post_Forum_Topic` (`Topic_idTopic` ASC);

CREATE INDEX `fk_Post_Forum_has_Topic_Post_Forum1_idx` ON `VeganHeaven`.`Post_Forum_Topic` (`Post_Forum_idPost_Forum` ASC);


-- -----------------------------------------------------
-- Table `VeganHeaven`.`Paniers_Annonces`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `VeganHeaven`.`Paniers_Annonces` (
  `Paniers_idPaniers` INT NOT NULL,
  `Annonces_idAnnonces` INT NOT NULL,
  PRIMARY KEY (`Paniers_idPaniers`, `Annonces_idAnnonces`),
  CONSTRAINT `fk_Paniers_has_Annonces_Paniers1`
    FOREIGN KEY (`Paniers_idPaniers`)
    REFERENCES `VeganHeaven`.`Paniers` (`idPaniers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Paniers_has_Annonces_Annonces2`
    FOREIGN KEY (`Annonces_idAnnonces`)
    REFERENCES `VeganHeaven`.`Annonces` (`idAnnonces`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Paniers_has_Annonces_Annonces1_idx` ON `VeganHeaven`.`Paniers_Annonces` (`Annonces_idAnnonces` ASC);


-- -----------------------------------------------------
-- Table `VeganHeaven`.`Paniers_Annonces`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `VeganHeaven`.`Paniers_Annonces` (
  `Paniers_idPaniers` INT NOT NULL,
  `Annonces_idAnnonces` INT NOT NULL,
  PRIMARY KEY (`Paniers_idPaniers`, `Annonces_idAnnonces`),
  CONSTRAINT `fk_Paniers_has_Annonces_Paniers1`
    FOREIGN KEY (`Paniers_idPaniers`)
    REFERENCES `VeganHeaven`.`Paniers` (`idPaniers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Paniers_has_Annonces_Annonces2`
    FOREIGN KEY (`Annonces_idAnnonces`)
    REFERENCES `VeganHeaven`.`Annonces` (`idAnnonces`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Paniers_has_Annonces_Annonces2_idx` ON `VeganHeaven`.`Paniers_Annonces` (`Annonces_idAnnonces` ASC);

CREATE INDEX `fk_Paniers_has_Annonces_Paniers1_idx` ON `VeganHeaven`.`Paniers_Annonces` (`Paniers_idPaniers` ASC);


-- -----------------------------------------------------
-- Table `VeganHeaven`.`Members_Transactions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `VeganHeaven`.`Members_Transactions` (
  `Members_idMembers` INT NOT NULL,
  `Transactions_idTransactions` INT NOT NULL,
  PRIMARY KEY (`Members_idMembers`, `Transactions_idTransactions`),
  CONSTRAINT `fk_Members_has_Transactions_Members1`
    FOREIGN KEY (`Members_idMembers`)
    REFERENCES `VeganHeaven`.`Members` (`idMembers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Members_has_Transactions_Transactions1`
    FOREIGN KEY (`Transactions_idTransactions`)
    REFERENCES `VeganHeaven`.`Transactions` (`idTransactions`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Members_has_Transactions_Transactions1_idx` ON `VeganHeaven`.`Members_Transactions` (`Transactions_idTransactions` ASC);

CREATE INDEX `fk_Members_has_Transactions_Members1_idx` ON `VeganHeaven`.`Members_Transactions` (`Members_idMembers` ASC);








